### ISSUE TITLE
Incorrect org.gnome.sdk version

### ISSUE THREAD

**Issue by rob-hills** [hbons/org.sparkleshare.SparkleShare#3]
The Build instructions for this project include this line:
```flatpak --user install gnome org.gnome.Sdk 3.28```
However, the trying to build the project gives the following error:
```error: org.gnome.Sdk 3.26 not installed
Failed to init: Unable to find sdk org.gnome.Sdk version 3.26
```
In org.sparkleshare.SparkleShare.json I see:
```    "sdk": "org.gnome.Sdk",
    "runtime": "org.gnome.Platform",
    "runtime-version": "3.26",
```
Should the line 4 in org.sparkleshare.SparkleShare.json be `"runtime-version": "3.28"`
or should README.md advise installing version 3.26 of the SDK?

**Comment by hbons** [comment]
try this branch https://github.com/hbons/org.sparkleshare.SparkleShare/blob/feature/appindicator/org.sparkleshare.SparkleShare.json with the 3.28 runtime/sdk installed. I assume you're trying to build the appindicator branch, but the instructions on the master branch still say 3.26?

**Comment by rob-hills** [comment]
Hmmm, I'd thought that was the branch I had cloned, however the version of org.sparkleshare.SparkleShare.json has 3.26 as SDK version.

I'm part-way through building, I think I'll kill it and start again with the URL you've specified above.

**Comment by rob-hills** [comment]
Sorry for the unnecessary distraction, just confirmed I was working with branch `master`
I'll clone the `appindicator` branch and start again.

**Comment by hbons** [comment]
No problem. I've added you to the Gitter chat room. It's easier to chat there if you run into more issues. :)
